### ISSUE TITLE
pipedoutput crash on Linux

### ISSUE THREAD

**Issue by Jemsterr** [Truinto/Nightinggale-ONI-mods#1]
[Player.log](https://github.com/Truinto/Nightinggale-ONI-mods/files/6840238/Player.log)

The only way to fix this is to unsubscribe and delete the mod folder.  I'll try doing that, disabling all the other mods and resubbing.

I'll post that log next.

**Comment by Jemsterr** [comment]
[Player.log](https://github.com/Truinto/Nightinggale-ONI-mods/files/6840259/Player.log)
With all other mods disabled.  I wish there was a way to unsubscribe to them all for a cleaner log, but I know I would miss several when I went to resubscribe.

**Comment by Truinto** [comment]
No need for unsubscribing. It's good to disable unrelated mods, but even that's not always mandatory.
Unfortunately there is no exception in this log. It's one of these rare crashes without any information. But I can tell it happens right before OilRefinery would have been patched.

**Comment by Truinto** [comment]
I will write a debug version. I will post it here. Please try it out for me then.

**Comment by Truinto** [comment]
Here is the file: [Debugging/PipedOutput.dll](https://github.com/Truinto/Nightinggale-ONI-mods/raw/master/src/PipedOutput/Debugging/PipedOutput.dll)
I hope this lights things up.

**Comment by Jemsterr** [comment]
Here's the debug.  (It took me quite a while to find that the local mod folder had to be named Local instead of local)
[Player.log](https://github.com/Truinto/Nightinggale-ONI-mods/files/6841484/Player.log)

**Comment by Truinto** [comment]
This confirms it is indeed the OilRefinery. I found a pattern. It's the first building where I patch this method and it being empty:
public override void DoPostConfigureComplete(GameObject go)

For whatever reason Harmony is fine patching it on Windows, but not on Linux/Mac. It is annoying, but fixable.

**Comment by Truinto** [comment]
Update it. Please test this version: https://github.com/Truinto/Nightinggale-ONI-mods/raw/master/src/PipedOutput/Debugging/PipedOutput.dll
It shouldn't crash anymore.

**Comment by Jemsterr** [comment]
Seems to be fixed.  Thank you.  When you close this ticket, I will know you have updated the Steam version and then I can resub and remove this local version.

**Comment by Truinto** [comment]
Thanks for your help.
