### ISSUE TITLE
Won't update to 1.4.2 on base game (Piped Output)

### ISSUE THREAD

**Issue by dezemberr** [Truinto/Nightinggale-ONI-mods#2]
Dropping this over here as requested. I'm on the base game without the DLC enabled (build `U40-493472-V`). I do use mod updater and have tried forcing an update more than once; however, it seems to be stuck on v1.4.1.0 and it's definitely not working in-game. Mod Updater shows that it looks like it's up-to-date but clearly not. I've gone through my mods and I'm not aware of any that should result in incompatibility issues. I checked the debug log and 1.4.1 seems to load in fine, just doesn't work.

**Comment by Truinto** [comment]
I had Mod Updater not work for me once. It worked again after deleting the config files for that mod.
C:\Users\%username%\Documents\Klei\OxygenNotIncluded\mods\config\ModUpdateDate

**Comment by Truinto** [comment]
Just checked. Recent version works with DLC disabled.
![pic](https://user-images.githubusercontent.com/47917181/151668775-080e3fe8-e0f9-488b-88e6-344e1a5c48be.png)

If you still have trouble you can install the mod locally. Just drop the files into a new folder in either "local" or "dev". Mods in the dev folder won't force stop the game after an exception (although in my experience it will crash anyways).
[PipedOutputV1.4.2.zip](https://github.com/Truinto/Nightinggale-ONI-mods/files/7964110/PipedOutputV1.4.2.zip)
![pic2](https://user-images.githubusercontent.com/47917181/151668958-294f4b16-9be9-4cda-a213-25f26bf4b1d1.png)

**Comment by dezemberr** [comment]
Hmm... Thanks, I'll give it a go. It definitely still won't update but I
did get it to show a blue output on one machine last night so that was
interesting. I'll report back.

**Comment by dezemberr** [comment]
Okay, so I downloaded the 1.4.2 zip, extracted it, dropped everything into
mods>dev and it still says 1.4.1??
https://i.imgur.com/vwVxURn.png

**Comment by dezemberr** [comment]
Okay, so it now seems to be magically working; however, the mod updater still doesn't show the correct version (DLC or otherwise). Do with this what you will? lol
